
query getRepositories($username: String!) {
  user(login: $username) {
    pinnedItems(first: 6) {
      totalCount
      edges {
        node {
          __typename
          ... on Repository {
            id
            name
            stargazerCount
            url
            primaryLanguage {
              name
              color
            }
            repositoryTopics(first: 2) {
              nodes {
                topic {
                  name
                  id
                }
              }
            }
            description
          }
        }
      }
    }
  }      
}
